# Generated by Django 5.0 on 2025-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturemodel',
            name='montant_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturemodel',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
