# Generated by Django 5.0 on 2025-12-22 15:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_facturemodel_montant_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colismodel',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='destinatairemodel',
            name='quartier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
