# Generated by Django 5.0 on 2025-12-22 22:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_colismodel_poids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colismodel',
            name='poids',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='destinatairemodel',
            name='quartier',
            field=models.CharField(max_length=100),
        ),
    ]
