# Generated by Django 5.0 on 2025-12-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_colismodel_poids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatairemodel',
            name='adresse_complete',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destinatairemodel',
            name='quartier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
