# Generated by Django 5.0 on 2025-12-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_destinatairemodel_adresse_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediteurmodel',
            name='adresse_complete',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expediteurmodel',
            name='quartier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediteurmodel',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
