# Generated by Django 5.0 on 2025-12-23 07:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_expediteurmodel_adresse_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colismodel',
            name='poids',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
