# Generated by Django 5.0 on 2025-12-23 21:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_colismodel_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='colismodel',
            name='frais_envoi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
