apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-kid
  labels:
    app: backend
    component: api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
        
        - name: migrate
          image: ghcr.io/VOTRE_ORG/kid-backend:latest  # À MODIFIER
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: backend-secret
      
      containers:
        - name: backend
          image: ghcr.io/VOTRE_ORG/kid-backend:latest  # À MODIFIER
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-kid
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
