apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app-kid
type: Opaque
stringData:
  POSTGRES_DB: kid_livraison
  POSTGRES_USER: kid_user
  POSTGRES_PASSWORD: changeme_in_prod  # À changer avec sealed-secrets ou external-secrets
  DB_HOST: postgres
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app-kid
type: Opaque
stringData:
  SECRET_KEY: changeme_django_secret_key_in_prod  # À changer avec sealed-secrets
